In [28]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/temporary/Train_Data.csv
/kaggle/input/capstone-testdata/Test_Data.csv

In [29]:
df=pd.read_csv('/kaggle/input/temporary/Train_Data.csv')

In [30]:
avg_values = {
    'ld': df['ld'].mean(),
    'm0': df['m0'].mean(),
    'm1': df['m1'].mean(),
    'm2': df['m2'].mean(),
    'm3': df['m3'].mean(),
    'm4': df['m4'].mean(),
    'm5': df['m5'].mean(),
    'm6': df['m6'].mean(),
    'm7': df['m7'].mean(),
    'm8': df['m8'].mean(),
    'm9': df['m9'].mean(),
    'm10': df['m10'].mean(),
    'm11': df['m11'].mean(),
    'm12': df['m12'].mean(),
    'm13': df['m13'].mean(),
    'm14': df['m14'].mean(),


}



df.fillna(value=avg_values, inplace=True)

In [31]:
df[['trash','ma']] = df['ma'].str.split('m', expand=True)
df=df.drop(['trash'],axis=1)
df['ma'] = df['ma'].astype(int)


def replace_with_ascii(text):
    return ''.join(str(ord(char)) for char in text)
df['pc'] = df['pc'].apply(replace_with_ascii)
df['pc'] = df['pc'].astype(int)

df.dropna(subset=['pred'], inplace=True)

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [33]:
# Assuming X contains the predictor variables and y contains the target variable
X = df.iloc[:, 0:18]  # Select the columns representing the predictor variables
y = df.iloc[:,18]  # Select the column representing the target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [34]:
df

,pc,ld,m0,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,ma,pred
0,121,83.71,63.0,7.2,52.5,14.0232,130.8300,12.4280,188.8425,8.9520,201.1905,9.2896,141.9075,16.096800,150.3390,12.488000,173.124000,78,0
1,121,108.94,31.5,12.8,84.0,13.2840,128.8350,13.5256,183.0990,8.8520,207.2385,8.4704,154.7805,13.330400,101.0205,12.509600,131.407500,78,0
2,69,169.65,0.0,5.6,73.5,14.5472,128.9295,13.6424,174.4680,8.9800,190.3125,11.3056,156.7650,15.334764,122.5350,11.713600,176.820000,76,1
3,120,122.42,31.5,7.2,63.0,15.0152,119.8575,12.3344,186.8580,10.7208,193.8195,10.6096,175.7490,15.334764,124.8030,13.842400,168.262500,55,0
4,69,125.43,94.5,7.2,42.0,14.4176,135.4290,14.5824,187.8135,9.3088,203.1540,9.8280,172.7040,14.472000,120.2145,12.521853,150.118500,76,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22579,69,139.08,73.5,7.2,84.0,13.8016,115.9725,13.8856,189.0000,8.6536,196.7490,9.2216,170.8770,17.374400,164.7240,12.572000,144.406500,76,1
22580,120,156.74,63.0,5.6,105.0,13.6464,130.2000,12.4688,180.3690,10.6984,212.6355,8.1152,167.8110,13.565600,129.5070,11.134400,168.530817,55,1
22581,119,115.63,147.0,4.8,31.5,13.4344,115.5000,13.5752,190.8900,9.6144,219.6810,9.3120,156.7440,15.971200,109.3680,12.848000,153.583500,78,0
22582,121,216.26,105.0,4.8,31.5,13.8176,112.5285,13.2408,166.8555,9.0160,200.3610,7.4760,174.7830,16.788800,135.1770,12.733600,158.098500,78,0
22583,69,120.65,31.5,6.4,42.0,14.8536,149.5305,13.1448,189.3570,10.0600,192.2970,9.0448,190.2495,16.443200,107.6355,12.722400,169.701000,76,0

In [35]:
test=pd.read_csv("/kaggle/input/capstone-testdata/Test_Data.csv")

In [36]:
avg_values_test = {
    'ld': test['ld'].mean(),
    'm0': test['m0'].mean(),
    'm1': test['m1'].mean(),
    'm2': test['m2'].mean(),
    'm3': test['m3'].mean(),
    'm4': test['m4'].mean(),
    'm5': test['m5'].mean(),
    'm6': test['m6'].mean(),
    'm7': test['m7'].mean(),
    'm8': test['m8'].mean(),
    'm9': test['m9'].mean(),
    'm10': test['m10'].mean(),
    'm11': test['m11'].mean(),
    'm12': test['m12'].mean(),
    'm13': test['m13'].mean(),
    'm14': test['m14'].mean(),


}


test.fillna(value=avg_values_test, inplace=True)

In [37]:
test[['trash','ma']] = test['ma'].str.split('m', expand=True)
test=test.drop(['trash'],axis=1)
test['ma'] = test['ma'].astype(int)


test['pc'] = test['pc'].apply(replace_with_ascii)
test['pc'] = test['pc'].astype(int)

test=test.drop(['index'],axis=1)

In [38]:
test

,pc,ld,m0,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,ma
0,69,156.46,73.5,8.8,105.0,13.2768,113.5365,13.9552,168.5460,8.5896,187.6560,8.3472,178.594500,14.31920,138.0435,12.700800,166.110000,76
1,121,58.87,84.0,12.8,42.0,14.4440,126.6930,13.6688,190.6275,10.1712,202.5870,8.5416,166.981500,15.59440,142.5690,11.683200,177.723000,78
2,119,139.68,126.0,3.2,73.5,14.2432,107.4885,13.8544,168.3255,10.2504,214.2735,11.3392,155.179500,16.02560,132.1005,13.010400,185.608500,78
3,122,194.06,52.5,6.4,105.0,14.5480,138.6105,13.5080,196.6545,10.6304,213.4650,9.9224,191.100000,14.82560,128.0475,12.198400,180.274500,75
4,120,173.14,42.0,8.0,136.5,14.9496,103.8765,13.8936,168.3570,9.6184,191.2050,9.9400,185.031000,13.86640,124.7610,12.524991,157.647000,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3981,122,109.45,126.0,4.0,94.5,14.6168,131.4495,13.1032,189.0840,8.3384,203.2275,9.6848,169.215523,14.63840,97.2510,12.333600,180.043500,75
3982,119,188.31,136.5,1.6,21.0,12.9032,115.1535,14.3616,189.4830,7.6680,183.8865,9.8032,172.294500,16.15120,110.7330,12.168000,204.550500,78
3983,69,80.99,31.5,4.8,115.5,15.0696,114.6810,14.0200,186.0810,9.2080,193.6200,9.1600,170.184000,15.35423,127.4700,13.501600,168.382988,76
3984,119,120.64,42.0,0.8,126.0,13.8960,123.6585,13.5496,187.8975,9.7944,189.0525,9.4752,173.029500,17.17280,113.0430,13.148000,164.241000,78
3985,119,115.73,199.5,4.0,10.5,14.2592,129.0555,13.8904,179.6865,8.8712,214.6410,8.8816,167.653500,15.46400,136.3635,11.872800,178.542000,78

In [39]:
'''import xgboost as xgb
import lightgbm as lgb
from sklearn.metrics import f1_score


# Train the XGBoost model
model = xgb.XGBClassifier(learning_rate=1.75, n_estimators=290, reg_lambda=0.1)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

f1 = f1_score(y_test, y_pred, average='macro')

print("F1 Score:", f1)'''

'import xgboost as xgb\nimport lightgbm as lgb\nfrom sklearn.metrics import f1_score\n\n\n# Train the XGBoost model\nmodel = xgb.XGBClassifier(learning_rate=1.75, n_estimators=290, reg_lambda=0.1)\nmodel.fit(X_train, y_train)\n\n# Make predictions on the test set\ny_pred = model.predict(X_test)\n\nf1 = f1_score(y_test, y_pred, average=\'macro\')\n\nprint("F1 Score:", f1)'

In [40]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier

base_estimator = GradientBoostingClassifier(learning_rate=2)
model = BaggingClassifier(estimator=base_estimator, n_estimators=55)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)

F1 Score: 0.2886178861788618

In [41]:
Y_pred=model.predict(test)
result=pd.DataFrame(Y_pred, columns=['pred'])
result.to_csv('svc.csv', index=False)